#544: set swagger api doc dynamic by gdl env
GlobalDigitalLibraryio/gdl-developer pull request #4
Opened 2019-02-11 08:46 UTC by kievu

2019-02-12 09:27 UTC, kstigen requested changes
i `SwaggerUI.tsx`i `componentDidMount()`: 

```
ui = SwaggerUI(...)
initOAuth({
   clientId: <FRA PROPS>,
   realm: "gdl-realm",
   appName: "gdl-swagger",
   scopeSeparator: " ",
   additionalQueryStringParams: {
      audience: "gdl_system"
   }
});
```

Du må også endre serverless.yml i deploy-repoet til å inkludere klient-iden

2019-02-12 09:27 UTC, kstigen commented on gatsby-config.js
> +
Her trenger vi å også hente `GDL_AUTH_CLIENT_ID` fra env. Den kan være `''` som default.

2019-02-12 09:27 UTC, kstigen commented on gatsby-config.js
> +    imageApiDocs: imageApiDocs()
Man må kanskje exportere `GDL_AUTH_CLIENT_ID` her for å bruke den andre steder?

2019-02-12 09:27 UTC, kstigen commented on src/pages/book-api.tsx
> +        <SwaggerUI
Gi med `GDL_AUTH_CLIENT_ID` her

2019-02-12 09:27 UTC, kstigen commented on src/pages/image-api.tsx
> +        <SwaggerUI
Gi med `GDL_AUTH_CLIENT_ID` her

2019-02-13 14:06 UTC, vikre commented on gatsby-config.js
> +
Siden pathen til API'ene nesten er like så lurer jeg på om vi kanskje kan lage bare **en** funksjon som tar inn API-navnet og får ut riktig url? Feks:
```
const apiDocs = (apiName) => {
  switch (GDL_ENVIRONMENT) {
    case 'dev':
      return `https://api.test.digitallibrary.io/${apiName}/api-docs`;
    case 'prod':
      return 'https://api.digitallibrary.io/${apiName}/api-docs';
    default:
      return `https://api.${GDL_ENVIRONMENT}.digitallibrary.io/${apiName}api-docs`;
  }
};
```

Også blir `exports` slik:
```
module.exports = {
  siteMetadata: {
    title: 'GDL developer portal',
    bookApiDocs: apiDocs('book-api'),
    imageApiDocs: apiDocs('image-api')
...
```

Dette er riktig nok ved antagelsen at APIene har nogen lunde lik path til hvor man finner dokumentasjonen med unntak av API-navnet :)

2019-02-13 15:13 UTC, kievu commented on gatsby-config.js
> +
Bra forslag 👍

2019-02-14 08:39 UTC, kievu commented on src/components/SwaggerUI.tsx
> +            firstNode.parentNode.removeChild(firstNode);
Swagger UI har ingen api for å skjule clientId, så måtte DOM manipulere for å fjerne den. Her er svaret jeg fikk @kstigen  https://github.com/swagger-api/swagger-ui/issues/5178

2019-02-14 16:14 UTC, kievu commented
Denne følger med: https://github.com/GlobalDigitalLibraryio/deploy/pull/167

2019-02-15 07:07 UTC, vikre commented on src/pages/oauth2-redirect.tsx
> +          oauthErrorMsg =
Noen grunn til at du ikke bruker template literals her? Så det blir noe ala dette:
```javascript
oauthErrorMsg = `[${qp.error}] ${qp.error_description ? qp.error_description : 'no accessCode received from the server.'} ${qp.error_uri ? `More info: ${qp.error_uri}` : ' ' }.`;
```

2019-02-15 07:11 UTC, vikre commented on src/components/SwaggerUI.tsx
> +            firstNode.parentNode.removeChild(firstNode);
@kievu legger du til den linken som en kommentar over her så vi har den?

2019-02-19 13:15 UTC, vikre approved these changes

2019-02-19 13:51 UTC, merged